<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.crm.qa.testcases.HomePageTest" tests="5" time="202.656" ignored="0" failures="1" timestamp="08 Feb 2023 07:17:39 GMT" skipped="0" hostname="PAKU-BLR-01" errors="0">
  <testcase name="homePageTitleTest" time="47.280" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="contactsLinkTest" time="39.033" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="dealsLinkTest" time="43.267" classname="com.crm.qa.testcases.HomePageTest"/>
  <testcase name="userValidation" time="34.423" classname="com.crm.qa.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="incorrect user expected [User: PANKAJ KUMAR] but found [  User: PANKAJ KUMAR]">
      <![CDATA[java.lang.AssertionError: incorrect user expected [User: PANKAJ KUMAR] but found [  User: PANKAJ KUMAR]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at com.crm.qa.pages.HomePage.verifyUserName(HomePage.java:45)
	at com.crm.qa.testcases.HomePageTest.userValidation(HomePageTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- userValidation -->
  <testcase name="tasksLinkTest" time="38.653" classname="com.crm.qa.testcases.HomePageTest"/>
</testsuite> <!-- com.crm.qa.testcases.HomePageTest -->
